server.port=8080
spring.application.name=VehicleRentalPlatform

# Folder where all .txt data files will be stored
app.data.dir=data

# Thymeleaf settings
spring.thymeleaf.cache=false

# Multipart file upload limits (fix HTTP 413 error)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB